### ISSUE TITLE
Reset DB

### ISSUE THREAD

**Issue by Pyrobolser** [adjoint-io/uplink-sdk-python#30]
I am having trouble with the method `uplink_reset_db(self, private_key, public_key)`

I cannot make it work in the **master** branch or in the __1.8 release__
It would be really nice to have an easy way to reset a test Uplink network, can you had a working example or some documentation about this?

Thank you,

**Comment by Pyrobolser** [comment]
Hello, do you guys have any extra info on this issue?

**Comment by Acentelles** [comment]
Hi @Pyrobolser 

`uplink_reset_db` is a method that can only be run in test mode.

I've just tested it and it works correctly. Make sure that you append `--test` when running an uplink node.
See https://github.com/adjoint-io/uplink-sdk-python/blob/master/uplink/client.py#L88

I copy the commands I used below in case they are useful:
- uplink:
```
stack exec uplink -- chain init -c config/node.config.local -b "leveldb://uplink1" -d node1 -p 8001 --rpc-port 8545 -v -k config/validators/auth0/key --test
```
- uplink-sdk-python:
```
from uplink import *
rpc = UplinkJsonRpc("localhost", 8545)
alice_pk, alice_sk = ecdsa_new()
alice_create_account_tx, alice_account_addr = rpc.uplink_create_account(
         private_key=alice_sk,
         public_key=alice_pk,
         from_address=None,
         metadata={'Name': 'Alice'},
         timezone="GMT"
     )
uplink_reset_db(alice_sk, alice_pk)
```

**Comment by Pyrobolser** [comment]
Thanks for your help.

When I try this code with the latest version on master or with the release version I have the following issue:

 `rpc.uplink_reset_db(alice_sk, alice_pk)`
>**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\uplink-sdk-python\uplink\client.py", line 97, in uplink_reset_db
    r, s = ecdsa_sign(private_key, address)
  File "\uplink-sdk-python\uplink\cryptography.py", line 122, in ecdsa_sign
    sig = sk.sign(msg, hashfunc=sha3.sha3_256, k=k)
  File "\uplink-sdk-python\venv\lib\site-packages\ecdsa\keys.py", line 254, in sign
    h = hashfunc(data).digest()
TypeError: Unicode-objects must be encoded before hashing**

**Comment by Acentelles** [comment]
@Pyrobolser I could reproduce the issue when using python3. I've just created a PR that fixes it

**Comment by Pyrobolser** [comment]
@Acentelles Thank you!
